# Configuración de Service Accounts para Cloud Run
# Basado en los permisos otorgados por Sebastián

project_id: agent-intelligence-gasco
region: us-central1

service_accounts:
  # Service Account principal para ADK Agent
  adk_agent:
    email: adk-agent-sa@agent-intelligence-gasco.iam.gserviceaccount.com
    display_name: "ADK Agent Service Account"
    description: "Interface conversacional inteligente con Vertex AI"
    roles:
      - roles/aiplatform.user
      - roles/bigquery.dataEditor  
      - roles/logging.logWriter
    cross_project_permissions:
      datalake-gasco:
        - roles/bigquery.dataViewer  # Lectura de tabla de facturas
        - roles/storage.objectViewer  # Lectura de PDFs
    
  # Service Account para MCP Toolbox
  mcp_toolbox:
    email: mcp-toolbox-sa@agent-intelligence-gasco.iam.gserviceaccount.com
    display_name: "MCP Toolbox Service Account"
    description: "Ejecutar herramientas BigQuery via protocolo MCP"
    roles:
      - roles/bigquery.jobUser
      - roles/bigquery.dataEditor
      - roles/logging.logWriter
    cross_project_permissions:
      datalake-gasco:
        - roles/bigquery.dataViewer
    
  # Service Account para File Service
  file_service:
    email: file-service-sa@agent-intelligence-gasco.iam.gserviceaccount.com
    display_name: "File Service Service Account"
    description: "Servir PDFs y generar ZIPs dinámicamente"
    roles:
      - roles/storage.admin
      - roles/bigquery.dataEditor
      - roles/logging.logWriter
    cross_project_permissions:
      datalake-gasco:
        - roles/storage.objectViewer

# Cloud Run Services Configuration
cloud_run_services:
  backend:
    name: invoice-backend
    service_account: adk-agent-sa@agent-intelligence-gasco.iam.gserviceaccount.com
    memory: 4Gi
    cpu: 2
    timeout: 3600
    min_instances: 0
    max_instances: 10
    
  frontend:
    name: invoice-frontend
    service_account: null  # No requiere service account específica
    memory: 512Mi
    cpu: 1
    timeout: 300
    min_instances: 0
    max_instances: 10

# Cross-project Resources
cross_project_resources:
  read_project: datalake-gasco
  bigquery_table: sap_analitico_facturas_pdf_qa.pdfs_modelo
  storage_bucket: miguel-test
  
  write_project: agent-intelligence-gasco
  zip_dataset: zip_operations
  zip_bucket: agent-intelligence-zips

# Security Notes
security_notes:
  - "Service Accounts configuradas por Sebastián con permisos mínimos"
  - "Cross-project access limitado a recursos específicos"
  - "No usar GOOGLE_APPLICATION_CREDENTIALS en Cloud Run"
  - "ADC (Application Default Credentials) configurado automáticamente"
